export default [
  {
    id: 1,
    postedOn: "02 Aug 2017 16:21:00 GMT",
    title: "Handyman / Carpenter",
    type: "Full time",
    location: "Melbourne",
    companyName: "Omni Trade Services",
    companyUrl: "https://www.hafele.com.au",
    skills: ["Immediate Start", "$50,000+", "Super+ Overtime"],
    link: "https://www.hafele.com.au",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Trade Supervisor",
    type: "Casual",
    location: "Melbourne",
    companyName: "Intact Group",
    companyUrl: "",
    skills: ["Immediate Start", "$50,000+", "Super+ Overtime"],
    link: "",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "Cabinet Makers & Production Assemblers",
    type: "Contract",
    location: "Melboure ",
    companyName: "Tink Recruitment",
    companyUrl: "",
    skills: ["Immediate Start", "$50,000+", "Super+ Overtime"],
    link: "",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Maintenance Technician (Handyman)",
    type: "Contract",
    location: "Melbourne",
    companyName: "GJK Facility Services",
    companyUrl: "",
    skills: ["Immediate Start", "$50,000+", "Super+ Overtime"],
    link: "https://facebook.com/careers",
  },
];
