export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "Frontend Developer/Programmer",
    type: "Full time",
    location: "Melbourne On Site",
    companyName: "Hafele Australia Pty Ltd",
    companyUrl: "https://www.hafele.com.au",
    skills: ["HTML/CSS/JS", "Node.js", "Angualr"],
    link: "https://www.hafele.com.au",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Graduate Software Developer - C Programmer",
    type: "Casual",
    location: "Melbourne On Site",
    companyName: "Optergy",
    companyUrl: "",
    skills: ["Node.js", "C++", "Express.js"],
    link: "",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "Applications Developer",
    type: "Contract",
    location: "Remote",
    companyName: "Deloitte Australia",
    companyUrl: "",
    skills: ["flutter", "Java", "HTML/CSS/JS"],
    link: "https://facebook.com/careers",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Developer Programmer",
    type: "Contract",
    location: "On Site",
    companyName: "Presilient Managed Services Pty Ltd",
    companyUrl: "",
    skills: ["Dot NET", "SQL", "Knockout JS"],
    link: "https://facebook.com/careers",
  },
];
